name: Lint

on: [push]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install ClangFormat
        run: sudo apt-get install -y clang-format

      - name: Run linters
        # Have to use this version until they release a newer version
        uses: wearerequired/lint-action@640cbd3acbeb113f05067c41db28f1836e1861ce

        with:
          clang_format: true
